export const colors = {
  ride_sys_color_surface_subtle: "ride_gl_color_neutral_10",
  ride_sys_color_surface_moderate: "ride_gl_color_neutral_20",
  ride_sys_color_surface_feedback_neutral_subtle: "ride_gl_color_neutral_30",
  ride_sys_color_surface_medium: "ride_gl_color_neutral_30",
  ride_sys_color_surface_fairly_strong: "ride_gl_color_neutral_60",
  ride_sys_color_surface_inverse: "ride_gl_color_neutral_100",
  ride_sys_color_surface_extreme: "ride_gl_color_neutral_90",
  ride_sys_color_surface_strong: "ride_gl_color_neutral_80",
  ride_sys_color_surface_quite_strong: "ride_gl_color_neutral_70",
  ride_sys_color_surface_default: "ride_gl_color_neutral_0",
  ride_sys_color_surface_disable: "#1433CC1A",

  ride_sys_color_background_subtle: "ride_gl_color_neutral_20",
  ride_sys_color_background_moderate: "ride_gl_color_neutral_30",
  ride_sys_color_background_strong: "ride_gl_color_neutral_100",

  ride_sys_color_glyph_subtle: "ride_gl_color_neutral_20",
  ride_sys_color_glyph_disabled: "ride_gl_color_neutral_50",
  ride_sys_color_glyph_strong: "ride_gl_color_neutral_70",
  ride_sys_color_glyph_medium: "ride_gl_color_neutral_60",
  ride_sys_color_glyph_extreme: "ride_gl_color_neutral_80",
  ride_sys_color_glyph_default: "ride_gl_color_neutral_100",

  ride_sys_color_border_default: "ride_gl_color_neutral_40",
  ride_sys_color_border_subtle: "ride_gl_color_neutral_50",
  ride_sys_color_border_moderate: "ride_gl_color_neutral_60",
  ride_sys_color_border_medium: "ride_gl_color_neutral_70",
  ride_sys_color_border_strong: "ride_gl_color_neutral_80",
  ride_sys_color_border_extreme: "ride_gl_color_neutral_90",
  ride_sys_color_border_focus: "ride_gl_color_skyblue_70",
  ride_sys_color_border_disable: "rgba(20, 51, 204, 0.2)",

  ride_sys_color_shape_subtle: "ride_gl_color_neutral_50",
  ride_sys_color_shape_default: "ride_gl_color_neutral_100",
  
  ride_sys_color_brand_dark: "ride_gl_color_accent_100",
  
  ride_sys_color_text_medium: "ride_gl_color_neutral_70",
  ride_sys_color_text_strong: "ride_gl_color_neutral_80",
  ride_sys_color_text_extreme: "ride_gl_color_neutral_100",
  ride_sys_color_text_disabled: "ride_gl_color_neutral_50",
  ride_sys_color_text_inverse: "ride_gl_color_neutral_0",
  ride_sys_transparent: "ride_gl_color_neutral_0",
} as const;
